version: 2

models:
  - name: customer_lifetime_value
    description: >
      Customer Lifetime Value model using RFM (Recency, Frequency, Monetary) analysis.
      Calculates customer segments based on purchasing behavior and predicts LTV scores.
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null

      - name: customer_name
        description: Full name of the customer

      - name: email
        description: Customer email address

      - name: segment
        description: Business segment (Enterprise, SMB, Consumer)

      - name: region
        description: Geographic region

      - name: customer_since
        description: Date customer was created

      - name: days_as_customer
        description: Number of days since customer creation

      - name: total_orders
        description: Total number of orders placed
        tests:
          - not_null

      - name: total_revenue
        description: Total revenue generated by customer

      - name: total_units
        description: Total units purchased

      - name: first_order_date
        description: Date of first order

      - name: last_order_date
        description: Date of most recent order

      - name: days_since_last_order
        description: Recency metric - days since last purchase

      - name: avg_order_value
        description: Average order value

      - name: avg_days_between_orders
        description: Average frequency between orders

      - name: recency_score
        description: RFM Recency score (1-5, 5 is best)

      - name: frequency_score
        description: RFM Frequency score (1-5, 5 is best)

      - name: monetary_score
        description: RFM Monetary score (1-5, 5 is best)

      - name: rfm_score
        description: Combined RFM score (sum of R, F, M)

      - name: ltv_score
        description: Calculated Lifetime Value score

      - name: customer_tier
        description: Customer tier classification (Platinum, Gold, Silver, Bronze)
        tests:
          - accepted_values:
              values: ['Platinum', 'Gold', 'Silver', 'Bronze']
